# Generated by Django 4.2.3 on 2023-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationalCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='suggestedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
