# Generated by Django 4.2.3 on 2023-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimumHourlySalary',
            field=models.FloatField(null=True),
        ),
    ]
