# Generated by Django 4.2.3 on 2023-07-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employee_nationalcode_employee_suggestedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=50)),
                ('jobDescription', models.TextField()),
                ('requiredSkills', models.TextField()),
                ('rules', models.TextField()),
                ('category', models.CharField(max_length=25)),
                ('subCategory', models.CharField(max_length=30)),
                ('minimumHourlySalary', models.FloatField()),
                ('address', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('salary', models.FloatField()),
                ('numberOfApplicants', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job')),
            ],
            options={
                'unique_together': {('job', 'date', 'startTime', 'endTime')},
            },
        ),
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shift')),
            ],
            options={
                'unique_together': {('shift', 'employee')},
            },
        ),
    ]
