# Generated by Django 4.2.3 on 2023-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job_has_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='numberOfApplicants',
            field=models.IntegerField(default=0),
        ),
    ]
