# Generated by Django 4.2.3 on 2023-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_manager_supporter_user_is_manager_user_is_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('H', 'مهمان داری'), ('R', 'خرده فروشی'), ('L', 'تدارکات')], max_length=25),
        ),
    ]
