# Generated by Django 4.2.3 on 2023-07-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('job', 'date', 'startTime', 'endTime')},
        ),
    ]
