# Generated by Django 4.2.3 on 2023-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Hospitality', 'مهمان داری'), ('Retail', 'خرده فروشی'), ('Logistics', 'تدارکات')], max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='subCategory',
            field=models.CharField(choices=[('Hospitality', (('Barista', 'باریستا'), ('Bartending', 'متصدی بار'), ('Catering', 'پذیرایی'), ('Chef de partie', 'سرآشپز'), ('Cleaning', 'نظافت چی'), ('Cloakroom Assistant', 'دستیار رخت کن'), ('Hosting', 'میزبانی'), ('Housekeeping', 'خانه داری'), ('Kitchen Porter', 'کارگر آشپزخانه'), ('Room Service', 'سرویس اتاق'), ('Sous-Chef', 'دستیار سرآشپز'), ('Waiter', 'پیشخدمت'))), ('Retail', (('Sales Associate', 'فروشنده'), ('Stock Assistant', 'مشاور سهام'))), ('Logistics', (('Driver', 'راننده'), ('Warehouse Assistant', 'انباردار')))], max_length=30),
        ),
    ]
