# Generated by Django 4.2.3 on 2023-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_job_category_alter_job_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'قبول شده'), ('Rejected', 'رد شده'), ('Pending', 'در حال بررسی')], max_length=20),
        ),
    ]
