# Generated by Django 4.2.3 on 2023-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, choices=[('AzerbayjanSharghi', 'آذربایجان شرقی'), ('AzerbayjanGharbi', 'آذربایجان غربی'), ('Ardebil', 'اردبیل'), ('Isfahan', 'اصفهان'), ('Alborz', 'البرز'), ('Ilam', 'ایلام'), ('Boshehr', 'بوشهر'), ('Tehran', 'تهران'), ('ChaharMahal', 'چهارمحال و بختیاری'), ('KhorasanJonobi', 'خراسان جنوبی'), ('KhorasanShomali', 'خراسان شمالی'), ('KhorasanRazavi', 'خراسان رضوی'), ('Khuzestan', 'کردستان'), ('Zanjan', 'زنجان'), ('Semnan', 'سمنان'), ('Sistan', 'سیستان و بلوچستان'), ('Fars', 'فارس'), ('Qazvin', 'قزوین'), ('Qom', 'قم'), ('Kordestan', 'کردستان'), ('Kerman', 'کرمان'), ('Kermanshah', 'کرمانشاه'), ('Kohgiloye', 'کهگیلویه و بویراحمد'), ('Golestan', 'گلستان'), ('Gilan', 'گیلان'), ('Lorestan', 'لرستان'), ('Mazandaran', 'مازندران'), ('Markazi', 'مرکزی'), ('Hormozgan', 'هرمزگان'), ('Hamedan', 'همدان'), ('Yazd', 'یزد')], max_length=50),
        ),
    ]
