# Generated by Django 4.2.3 on 2023-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_picture_employee_profilepicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_signup',
            field=models.BooleanField(default=False),
        ),
    ]
